
DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    funfact TEXT
);


INSERT INTO countries (name, funfact) VALUES
('Albania', 'Albania has a coastline along both the Adriatic and Ionian Seas.'),
('Andorra', 'Andorra is located in the Pyrenees mountains between France and Spain.'),
('Austria', 'Austria is over 60% covered by the Alps.'),
('Belarus', 'Belarus is known as the “Land of Lakes,” with more than 11,000 lakes.'),
('Belgium', 'Belgium’s highest point, Signal de Botrange, is only 694 meters tall.'),
('Bosnia and Herzegovina', 'Bosnia and Herzegovina has a tiny coastline of just 20 km along the Adriatic Sea.'),
('Bulgaria', 'Bulgaria is home to Europe’s oldest mountain range, the Balkan Mountains.'),
('Croatia', 'Croatia has over 1,000 islands along its Adriatic coast.'),
('Cyprus', 'Cyprus is the third largest island in the Mediterranean Sea.'),
('Czech Republic', 'The Czech Republic has no coastline and is completely landlocked.'),
('Denmark', 'Denmark has more than 400 islands, but only about 70 are inhabited.'),
('Estonia', 'Estonia has more than 2,000 islands in the Baltic Sea.'),
('Finland', 'Finland is the “Land of a Thousand Lakes” — but actually has around 188,000 lakes.'),
('France', 'France is the largest country in the European Union by land area.'),
('Germany', 'Germany shares borders with 9 different countries — the most in Europe.'),
('Greece', 'Greece has around 6,000 islands, though only about 200 are inhabited.'),
('Hungary', 'Hungary is home to Lake Balaton, the largest lake in Central Europe.'),
('Iceland', 'Iceland sits on the Mid-Atlantic Ridge, where two tectonic plates meet.'),
('Ireland', 'Ireland is famous for its lush green landscape, earning it the nickname “Emerald Isle.”'),
('Italy', 'Italy is a boot-shaped peninsula surrounded by the Mediterranean Sea.'),
('Kosovo', 'Kosovo is one of the most mountainous countries in the Balkans.'),
('Latvia', 'Over half of Latvia’s territory is covered by forests.'),
('Liechtenstein', 'Liechtenstein is entirely located in the Alps and has no airport.'),
('Lithuania', 'Lithuania’s landscape is flat, with its highest hill only 294 meters tall.'),
('Luxembourg', 'Luxembourg has dense forests in the Ardennes in the north and rolling hills in the south.'),
('Malta', 'Malta is one of the world’s smallest island nations, with no rivers or mountains.'),
('Moldova', 'Moldova has gently rolling hills but no mountains, and no coastline.'),
('Monaco', 'Monaco is the world’s second smallest country, squeezed between France and the Mediterranean Sea.'),
('Montenegro', 'Montenegro is known for its dramatic mountains and the Bay of Kotor, a fjord-like inlet.'),
('Netherlands', 'About one-third of the Netherlands lies below sea level.'),
('North Macedonia', 'North Macedonia has many mountains and lakes, including Lake Ohrid, one of Europe’s oldest.'),
('Norway', 'Norway is famous for its fjords, carved by glaciers.'),
('Poland', 'Poland has a long coastline along the Baltic Sea and the Carpathian Mountains in the south.'),
('Portugal', 'Portugal’s Algarve region is famous for its dramatic coastal cliffs.'),
('Romania', 'The Danube River forms a huge delta in Romania before entering the Black Sea.'),
('San Marino', 'San Marino is built entirely on the slopes of Mount Titano.'),
('Serbia', 'The Danube River flows through Serbia, making it a key European waterway.'),
('Slovakia', 'Slovakia has over 100 castles and is mostly covered by the Carpathian Mountains.'),
('Slovenia', 'Slovenia is the only country in Europe that touches the Alps, the Mediterranean, the Pannonian Plain, and the Dinaric Alps.'),
('Spain', 'Spain is the most mountainous country in Europe after Switzerland.'),
('Sweden', 'Sweden has thousands of coastal islands and inland lakes.'),
('Switzerland', 'Switzerland is home to the Alps and has over 1,500 lakes.'),
('Ukraine', 'Ukraine is the largest country entirely in Europe by land area.'),
('United Kingdom', 'The UK is an island nation surrounded by the Atlantic Ocean, the North Sea, and the English Channel.');
